In [1]:
import json
import pandas as pd
import os

In [3]:
with open(r"datasets/codebooks.json", "r") as f:
    codebooks = json.load(f)

In [4]:
df = pd.DataFrame(codebooks)
df

,codebookKey,carCompany,carModel,carVersion,publicDate,options,carFuel,carWheelDrive,numOfSeat,carGearBox,payload,carType,engineCapacity,nameOld,nameNew,startYear,endYear
0,acura-mdx-sh-awd,ACURA,MDX,SH-AWD,14-11-2023,None,None,[],7.0,None,[],SUV,NaN,"[ACURA MDX SH AWD, ACURA MDX SPORT SH AWD, ACU...",[],NaN,2011.0
1,acura-legend-2.7-v6-at,ACURA,LEGEND,2.7 V6 AT,14-11-2023,None,None,[],5.0,None,[],SEDAN,NaN,"[ACURA LEGEND 2.7 V6, ACURA Legend 2.7 V6 AT, ...",[],NaN,NaN
2,acura-legend-3.2-v6,ACURA,LEGEND,3.2 V6,14-11-2023,None,None,[],5.0,None,[],SEDAN,NaN,[],[],NaN,NaN
3,acura-tsx-2.4-at,ACURA,TSX,2.4 AT,28-10-2025,None,None,[],NaN,None,[],SEDAN,NaN,[],[],NaN,NaN
4,acura-cl-3.0-at,ACURA,CL,3.0 AT,26-05-2024,None,None,[],4.0,None,[],None,NaN,[],[],NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3142,zotye-z300-1.6-at,ZOTYE,Z300,1.6 AT,14-11-2023,None,None,[],5.0,None,[],SEDAN,NaN,[],[],2015.0,2015.0
3143,zotye-x5-1.5t,ZOTYE,X5,1.5T,04-12-2025,None,None,[],NaN,None,[],None,NaN,[],[],NaN,NaN
3144,zotye-z8-2.0-at-7-cho,ZOTYE,Z8,2.0 AT (7 CHO),23-06-2025,None,None,[],7.0,None,[],SUV,2.0,[],[],NaN,NaN
3145,zotye-z8-2.0-at,ZOTYE,Z8,2.0 AT,23-06-2025,None,None,[],5.0,None,[],SUV,2.0,[],[],NaN,NaN
3146,zotye-hunter-1.3-mt,ZOTYE,HUNTER,1.3 MT,15-12-2023,None,None,[],5.0,None,[],SUV,NaN,[],[],NaN,NaN

In [5]:
df_2 = df['carCompany'].value_counts().reset_index()
df_2.sort_values(by='carCompany', ascending=True, inplace=True)
df_2

      carCompany  count
40         ACURA     13
87          AION      1
76    ALFA ROMEO      2
91          ASIA      1
55  ASTON MARTIN      9
..           ...    ...
23         VOLVO     37
97           WEY      1
56        WULING      8
75         ZEEKR      3
48         ZOTYE     11

[98 rows x 2 columns]

In [6]:
from classify.data import dataset

data = dataset.ClassificationDataModule(
    data_dir= r"datasets/dataset_2",
    batch_size=32,
    num_workers=2,
    )

train_dict, val_dict = data.setup()

/home/lam/miniforge3/lib/python3.14/site-packages/albumentations/core/validation.py:114: UserWarning: ShiftScaleRotate is a special case of Affine transform. Please use Affine transform instead.
  original_init(self, **validated_kwargs)

In [7]:
train_df = pd.DataFrame(list(train_dict.items()), columns=['carCompany', 'count']).explode('count')
train_df = train_df.groupby('carCompany')['count'].count().reset_index().sort_values(by='carCompany', ascending=True)

train_df.at[1, 'carCompany'] = "ALFA ROMEO"
train_df.at[13, 'carCompany'] = "CHERY"
train_df.at[57, 'carCompany'] = "LYNK & CO"
train_df.at[63, 'carCompany'] = "MERCEDES-BENZ-BENZ-BENZ"

train_df

     carCompany  count
0         ACURA    182
1    ALFA ROMEO     47
2          AUDI    249
3          BAIC    353
4       BENTLEY     61
..          ...    ...
97        VOLVO    244
98          WAW     44
99       WULING     80
100       ZEEKR    195
101       ZOTYE    121

[102 rows x 2 columns]

In [8]:
df_merge = pd.merge(df_2, train_df, on='carCompany', how='outer', suffixes=('_codebooks', '_train'))
df_merge

       carCompany  count_codebooks  count_train
0           ACURA             13.0        182.0
1            AION              1.0          NaN
2      ALFA ROMEO              2.0         47.0
3            ASIA              1.0          NaN
4    ASTON MARTIN              9.0          NaN
..            ...              ...          ...
121           WAW              NaN         44.0
122           WEY              1.0          NaN
123        WULING              8.0         80.0
124         ZEEKR              3.0        195.0
125         ZOTYE             11.0        121.0

[126 rows x 3 columns]

In [9]:
df_merge

       carCompany  count_codebooks  count_train
0           ACURA             13.0        182.0
1            AION              1.0          NaN
2      ALFA ROMEO              2.0         47.0
3            ASIA              1.0          NaN
4    ASTON MARTIN              9.0          NaN
..            ...              ...          ...
121           WAW              NaN         44.0
122           WEY              1.0          NaN
123        WULING              8.0         80.0
124         ZEEKR              3.0        195.0
125         ZOTYE             11.0        121.0

[126 rows x 3 columns]

In [10]:
df.to_excel("datasets/codebooks.xlsx", index=False)

In [1]:
from classify.data import dataset

data = dataset.ClassificationDataModule(
    data_dir= r"datasets/dataset_2",
    batch_size=32,
    num_workers=2,
    )

train_dict, val_dict = data.setup()

/home/lam/miniforge3/lib/python3.14/site-packages/albumentations/core/validation.py:114: UserWarning: ShiftScaleRotate is a special case of Affine transform. Please use Affine transform instead.
  original_init(self, **validated_kwargs)

In [10]:
list(train_dict.items())

[('ACURA',
  ['datasets/dataset_2/train/ACURA/1766568713055_ACURA_100_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568713078_ACURA_105_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568713099_ACURA_106_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568713124_ACURA_108_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568713153_ACURA_109_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568713159_ACURA_10_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568713180_ACURA_110_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568713211_ACURA_111_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568713243_ACURA_115_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568713263_ACURA_117_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568713284_ACURA_118_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568713312_ACURA_119_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568713937_ACURA_346_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568758776_ACURA_121_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568758799_ACURA_123_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568758826_ACURA_124_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568758852_ACURA_126_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568758863_ACURA_12_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568758887_ACURA_132_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568758915_ACURA_141_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568758940_ACURA_143_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568758963_ACURA_144_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568758992_ACURA_147_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568759024_ACURA_148_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568759054_ACURA_149_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568759075_ACURA_153_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568759107_ACURA_155_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568759129_ACURA_156_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568759151_ACURA_157_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568759155_ACURA_158_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568759174_ACURA_159_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568759197_ACURA_161_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765190_ACURA_162_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765213_ACURA_163_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765238_ACURA_166_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765258_ACURA_170_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765278_ACURA_173_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765304_ACURA_176_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765330_ACURA_177_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765365_ACURA_189_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765371_ACURA_18_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765405_ACURA_196_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765410_ACURA_19_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765440_ACURA_200_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765471_ACURA_204_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765497_ACURA_209_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765510_ACURA_382_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765542_ACURA_384_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765565_ACURA_385_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765588_ACURA_386_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765597_ACURA_38_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765620_ACURA_392_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765642_ACURA_398_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765651_ACURA_3_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765676_ACURA_401_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765698_ACURA_403_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765721_ACURA_406_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765766_ACURA_412_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765787_ACURA_416_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765811_ACURA_417_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765830_ACURA_418_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765838_ACURA_419_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765846_ACURA_41_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765873_ACURA_420_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765896_ACURA_421_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765920_ACURA_428_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765946_ACURA_430_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765968_ACURA_437_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568765995_ACURA_441_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766026_ACURA_442_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766048_ACURA_446_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766078_ACURA_449_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766114_ACURA_453_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766138_ACURA_454_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766164_ACURA_455_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766189_ACURA_456_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766195_ACURA_457_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766205_ACURA_45_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766231_ACURA_460_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766255_ACURA_464_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766285_ACURA_465_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766311_ACURA_466_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766334_ACURA_467_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568766362_ACURA_470_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772409_ACURA_471_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772433_ACURA_480_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772457_ACURA_482_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772480_ACURA_484_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772509_ACURA_487_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772541_ACURA_491_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772567_ACURA_493_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772594_ACURA_494_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772602_ACURA_497_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772623_ACURA_498_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772658_ACURA_509_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772697_ACURA_510_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772718_ACURA_512_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772747_ACURA_515_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772778_ACURA_516_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772784_ACURA_51_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772828_ACURA_524_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772852_ACURA_525_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772871_ACURA_528_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772883_ACURA_52_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772909_ACURA_53_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772920_ACURA_57_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772925_ACURA_5_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772956_ACURA_61_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568772985_ACURA_62_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773011_ACURA_66_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773038_ACURA_69_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773064_ACURA_70_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773091_ACURA_71_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773124_ACURA_74_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773150_ACURA_76_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773179_ACURA_77_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773207_ACURA_83_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773234_ACURA_84_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773258_ACURA_88_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773264_ACURA_312_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773294_ACURA_314_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773319_ACURA_321_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773344_ACURA_324_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773366_ACURA_326_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773394_ACURA_329_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773417_ACURA_333_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773447_ACURA_335_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773492_ACURA_210_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773519_ACURA_211_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773548_ACURA_213_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773573_ACURA_214_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773593_ACURA_215_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773622_ACURA_217_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773635_ACURA_21_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568773661_ACURA_221_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779664_ACURA_227_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779673_ACURA_263_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779692_ACURA_265_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779714_ACURA_269_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779738_ACURA_273_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779759_ACURA_276_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779777_ACURA_277_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779807_ACURA_279_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779830_ACURA_284_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779855_ACURA_289_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779861_ACURA_89_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779892_ACURA_92_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779920_ACURA_94_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568779944_ACURA_95_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823275_ACURA_347_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823286_ACURA_34_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823305_ACURA_355_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823331_ACURA_358_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823357_ACURA_360_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823384_ACURA_369_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823412_ACURA_370_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823437_ACURA_371_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823467_ACURA_376_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823495_ACURA_379_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823531_ACURA_380_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823541_ACURA_23_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823575_ACURA_248_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823603_ACURA_249_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823612_ACURA_24_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823641_ACURA_251_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823667_ACURA_252_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823687_ACURA_253_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823712_ACURA_256_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823737_ACURA_258_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823765_ACURA_290_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823791_ACURA_291_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823818_ACURA_293_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823847_ACURA_297_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823877_ACURA_298_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823886_ACURA_29_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823893_ACURA_2_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823926_ACURA_300_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823953_ACURA_301_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823977_ACURA_304_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568823998_ACURA_307_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568824021_ACURA_309_001.jpg',
   'datasets/dataset_2/train/ACURA/1766568824046_ACURA_310_001.jpg']),
 ('AION',
  ['datasets/dataset_2/train/AION/Guazi_AION_e6uub23sgk_9_crop0_245_161_336.png',
   'datasets/dataset_2/train/AION/Guazi_AION_jbpvrht67g_8_crop2_437_147_482.png',
   'datasets/dataset_2/train/AION/Guazi_AION_uup36n63mq_8_crop0_352_116_429.png',
   'datasets/dataset_2/train/AION/Guazi_AION_6uhalktsmy_8_crop79_348_235_410.png',
   'datasets/dataset_2/train/AION/Guazi_AION_dbud59pmgs_9_crop35_140_179_252.png',
   'datasets/dataset_2/train/AION/Guazi_AION_k5gvk27m3a_5_crop92_400_203_457.png',
   'datasets/dataset_2/train/AION/Guazi_AION_ksckj5ngbr_22_crop0_749_305_829.png',
   'datasets/dataset_2/train/AION/Guazi_AION_tre8ba7g4e_8_crop24_479_284_582.png',
   'datasets/dataset_2/train/AION/Guazi_AION_26ecc987q3_1_crop334_596_438_658.png',
   'datasets/dataset_2/train/AION/Guazi_AION_26ecc987q3_2_crop705_715_911_760.png',
   'datasets/dataset_2/train/AION/Guazi_AION_26ecc987q3_5_crop585_657_888_722.png',
   'datasets/dataset_2/train/AION/Guazi_AION_26ecc987q3_6_crop334_551_432_617.png',
   'datasets/dataset_2/train/AION/Guazi_AION_26tr4cnrkp_1_crop309_488_364_518.png',
   'datasets/dataset_2/train/AION/Guazi_AION_26tr4cnrkp_2_crop618_531_761_563.png',
   'datasets/dataset_2/train/AION/Guazi_AION_26tr4cnrkp_5_crop582_456_791_493.png',
   'datasets/dataset_2/train/AION/Guazi_AION_26tr4cnrkp_6_crop320_459_410_496.png',
   'datasets/dataset_2/train/AION/Guazi_AION_2nphwf6us7_1_crop241_424_308_463.png',
   'datasets/dataset_2/train/AION/Guazi_AION_2nphwf6us7_3_crop944_452_989_479.png',
   'datasets/dataset_2/train/AION/Guazi_AION_2nphwf6us7_4_crop854_410_941_452.png',
   'datasets/dataset_2/train/AION/Guazi_AION_2nphwf6us7_5_crop549_459_711_489.png',
   'datasets/dataset_2/train/AION/Guazi_AION_2nphwf6us7_6_crop331_426_423_462.png',
   'datasets/dataset_2/train/AION/Guazi_AION_2ugsg6ngwa_1_crop291_617_410_690.png',
   'datasets/dataset_2/train/AION/Guazi_AION_2ugsg6ngwa_2_crop693_893_920_949.png',
   'datasets/dataset_2/train/AION/Guazi_AION_2ugsg6ngwa_6_crop169_627_297_717.png',
   'datasets/dataset_2/train/AION/Guazi_AION_4sqwync6fh_1_crop147_468_251_529.png',
   'datasets/dataset_2/train/AION/Guazi_AION_4sqwync6fh_2_crop548_593_750_630.png',
   'datasets/dataset_2/train/AION/Guazi_AION_4sqwync6fh_5_crop502_534_764_583.png',
   'datasets/dataset_2/train/AION/Guazi_AION_4sqwync6fh_6_crop223_437_360_482.png',
   'datasets/dataset_2/train/AION/Guazi_AION_4x847wrdru_1_crop286_416_370_454.png',
   'datasets/dataset_2/train/AION/Guazi_AION_4x847wrdru_2_crop594_531_715_555.png',
   'datasets/dataset_2/train/AION/Guazi_AION_4x847wrdru_5_crop577_436_731_459.png',
   'datasets/dataset_2/train/AION/Guazi_AION_53xwymhg8p_1_crop415_778_555_874.png',
   'datasets/dataset_2/train/AION/Guazi_AION_53xwymhg8p_6_crop137_458_232_501.png',
   'datasets/dataset_2/train/AION/Guazi_AION_6qvwuxa6d6_1_crop453_549_644_610.png',
   'datasets/dataset_2/train/AION/Guazi_AION_6qvwuxa6d6_6_crop559_505_832_583.png',
   'datasets/dataset_2/train/AION/Guazi_AION_6qvwuxa6d6_6_crop568_508_834_587.png',
   'datasets/dataset_2/train/AION/Guazi_AION_6uhalktsmy_1_crop241_478_355_520.png',
   'datasets/dataset_2/train/AION/Guazi_AION_6uhalktsmy_2_crop592_526_788_564.png',
   'datasets/dataset_2/train/AION/Guazi_AION_6uhalktsmy_5_crop589_440_858_488.png',
   'datasets/dataset_2/train/AION/Guazi_AION_6uhalktsmy_5_crop591_440_858_488.png',
   'datasets/dataset_2/train/AION/Guazi_AION_7jurf8gwuz_7_crop168_378_233_394.png',
   'datasets/dataset_2/train/AION/Guazi_AION_7jurf8gwuz_8_crop413_413_478_424.png',
   'datasets/dataset_2/train/AION/Guazi_AION_7mj9zz8mmq_1_crop349_502_432_540.png',
   'datasets/dataset_2/train/AION/Guazi_AION_7mj9zz8mmq_2_crop679_587_839_620.png',
   'datasets/dataset_2/train/AION/Guazi_AION_7mj9zz8mmq_6_crop339_383_469_439.png',
   'datasets/dataset_2/train/AION/Guazi_AION_86bw4qgsf7_1_crop145_305_194_320.png',
   'datasets/dataset_2/train/AION/Guazi_AION_86bw4qgsf7_6_crop218_418_375_467.png',
   'datasets/dataset_2/train/AION/Guazi_AION_88ch6lzbj2_2_crop572_515_714_543.png',
   'datasets/dataset_2/train/AION/Guazi_AION_88ch6lzbj2_5_crop536_455_742_492.png',
   'datasets/dataset_2/train/AION/Guazi_AION_8xehs7w5wy_1_crop346_602_451_637.png',
   'datasets/dataset_2/train/AION/Guazi_AION_8xehs7w5wy_6_crop320_512_459_551.png',
   'datasets/dataset_2/train/AION/Guazi_AION_9pbvjuwtg2_1_crop277_639_375_661.png',
   'datasets/dataset_2/train/AION/Guazi_AION_9pbvjuwtg2_2_crop714_561_900_596.png',
   'datasets/dataset_2/train/AION/Guazi_AION_9pbvjuwtg2_6_crop205_599_487_634.png',
   'datasets/dataset_2/train/AION/Guazi_AION_9pbvjuwtg2_6_crop505_711_570_736.png',
   'datasets/dataset_2/train/AION/Guazi_AION_9pvfvt7lcb_1_crop358_706_480_738.png',
   'datasets/dataset_2/train/AION/Guazi_AION_9pvfvt7lcb_2_crop543_475_725_515.png',
   'datasets/dataset_2/train/AION/Guazi_AION_9pvfvt7lcb_5_crop546_462_851_519.png',
   'datasets/dataset_2/train/AION/Guazi_AION_9pvfvt7lcb_6_crop252_402_396_462.png',
   'datasets/dataset_2/train/AION/Guazi_AION_9ubpk7s3f3_1_crop264_479_323_512.png',
   'datasets/dataset_2/train/AION/Guazi_AION_9ubpk7s3f3_2_crop544_557_677_582.png',
   'datasets/dataset_2/train/AION/Guazi_AION_9ubpk7s3f3_5_crop541_481_736_511.png',
   'datasets/dataset_2/train/AION/Guazi_AION_9ubpk7s3f3_6_crop232_415_327_460.png',
   'datasets/dataset_2/train/AION/Guazi_AION_aelqf8xjp4_1_crop394_481_532_534.png',
   'datasets/dataset_2/train/AION/Guazi_AION_aelqf8xjp4_2_crop572_533_750_567.png',
   'datasets/dataset_2/train/AION/Guazi_AION_aelqf8xjp4_5_crop459_492_700_540.png',
   'datasets/dataset_2/train/AION/Guazi_AION_aelqf8xjp4_5_crop461_492_701_540.png',
   'datasets/dataset_2/train/AION/Guazi_AION_aelqf8xjp4_6_crop345_536_524_594.png',
   'datasets/dataset_2/train/AION/Guazi_AION_aelqf8xjp4_8_crop159_450_303_504.png',
   'datasets/dataset_2/train/AION/Guazi_AION_aelqf8xjp4_9_crop137_460_370_518.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bgjqg9gpaf_1_crop175_461_258_509.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bgjqg9gpaf_2_crop557_511_742_549.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bgjqg9gpaf_5_crop528_473_807_522.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bgjqg9gpaf_5_crop529_474_807_523.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bgjqg9gpaf_6_crop139_402_283_465.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bju84c3qem_2_crop614_559_733_586.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bju84c3qem_5_crop542_424_740_460.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bju84c3qem_6_crop353_371_488_438.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bkfgpngs4z_1_crop250_449_336_495.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bkfgpngs4z_2_crop539_542_695_573.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bkfgpngs4z_3_crop864_468_948_517.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bkfgpngs4z_4_crop836_436_970_491.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bkfgpngs4z_5_crop511_475_740_520.png',
   'datasets/dataset_2/train/AION/Guazi_AION_br9jnqh6mk_1_crop353_790_543_859.png',
   'datasets/dataset_2/train/AION/Guazi_AION_br9jnqh6mk_4_crop306_633_503_697.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bxpfgahrzu_1_crop284_753_371_805.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bxpfgahrzu_8_crop150_470_292_556.png',
   'datasets/dataset_2/train/AION/Guazi_AION_bxwha4jgnk_1_crop220_464_414_522.png',

In [55]:
df = pd.DataFrame(list(train_dict.items()), columns=['carCompany', 'count']).explode('count')
df_val = pd.DataFrame(list(val_dict.items()), columns=['carCompany', 'count']).explode('count')

In [56]:
df

    carCompany                                              count
0        ACURA  datasets/dataset_2/train/ACURA/1766568713055_A...
0        ACURA  datasets/dataset_2/train/ACURA/1766568713078_A...
0        ACURA  datasets/dataset_2/train/ACURA/1766568713099_A...
0        ACURA  datasets/dataset_2/train/ACURA/1766568713124_A...
0        ACURA  datasets/dataset_2/train/ACURA/1766568713153_A...
..         ...                                                ...
125      ZOTYE  datasets/dataset_2/train/ZOTYE/1766570304270_Z...
125      ZOTYE  datasets/dataset_2/train/ZOTYE/1766570304276_Z...
125      ZOTYE  datasets/dataset_2/train/ZOTYE/1766570304281_Z...
125      ZOTYE  datasets/dataset_2/train/ZOTYE/1766570304288_Z...
125      ZOTYE  datasets/dataset_2/train/ZOTYE/1766570304299_Z...

[28700 rows x 2 columns]

In [60]:
df_count1 = df.groupby('carCompany')['count'].count().reset_index().sort_values(by='carCompany', ascending=True)
df_count1.columns = ['carCompany', 'count_train']
df_count2 = df_val.groupby('carCompany')['count'].count().reset_index().sort_values(by='carCompany', ascending=True)
df_count2.columns = ['carCompany', 'count_val']
df_count = pd.merge(df_count1, df_count2, on='carCompany', how='outer')
df_count.columns = ['Các lớp', 'Số lượng mẫu trong tập train ngày 15/6/2026', 'Số lượng mẫu trong tập val ngày 15/6/2026']
df_count = df_count.replace({
    "ALFA_ROMEO": "ALFA ROMEO",
    "CHEYRY": "CHERY",
    "LYNK&CO": "LYNK & CO",
    "MERCEDES-BENZ-BENZ-BENZ": "MERCEDES-BENZ"
})
df_count

,Các lớp,Số lượng mẫu trong tập train ngày 15/6/2026,Số lượng mẫu trong tập val ngày 15/6/2026
0,ACURA,182,45
1,AION,437,110
2,ALFA ROMEO,47,7
3,ASIA MOTOR,181,46
4,ASTON MARTIN,405,102
...,...,...,...
121,WAW,44,10
122,WEY,209,52
123,WULING,80,19
124,ZEEKR,195,73
125,ZOTYE,121,20

In [63]:
df2 = pd.read_excel("/home/lam/Documents/Book 1.xlsx")
df2["Các lớp"] = df2["Các lớp"].replace({
    "ALFA_ROMEO": "ALFA ROMEO",
    "CHERRY": "CHERY",
    "LYNK&CO": "LYNK & CO",
    "MERCEDES": "MERCEDES-BENZ"
})
df2

,Các lớp,Số data tập thử ngày 1/6/2026,Số data tập huấn luyện ngày 1/6/2026,Số data tập thử ban đầu,Số data tập huấn luyện ban đầu
0,ACURA,45,182,45,182
1,ALFA ROMEO,7,47,7,47
2,AUDI,62,249,62,249
3,BAIC,72,353,72,353
4,BENTLEY,10,61,10,61
...,...,...,...,...,...
97,VOLVO,55,244,25,100
98,WAW,10,44,10,44
99,WULING,19,80,19,80
100,ZEEKR,73,195,0,0
101,ZOTYE,20,121,20,121

In [64]:
df3 = pd.merge(df2, df_count, how="outer")
df3.fillna(0, inplace=True)
df3.to_excel("/home/lam/Documents/summary.xlsx", index=False)
df3

,Các lớp,Số data tập thử ngày 1/6/2026,Số data tập huấn luyện ngày 1/6/2026,Số data tập thử ban đầu,Số data tập huấn luyện ban đầu,Số lượng mẫu trong tập train ngày 15/6/2026,Số lượng mẫu trong tập val ngày 15/6/2026
0,ACURA,45.0,182.0,45.0,182.0,182,45
1,AION,0.0,0.0,0.0,0.0,437,110
2,ALFA ROMEO,7.0,47.0,7.0,47.0,47,7
3,ASIA MOTOR,0.0,0.0,0.0,0.0,181,46
4,ASTON MARTIN,0.0,0.0,0.0,0.0,405,102
...,...,...,...,...,...,...,...
121,WAW,10.0,44.0,10.0,44.0,44,10
122,WEY,0.0,0.0,0.0,0.0,209,52
123,WULING,19.0,80.0,19.0,80.0,80,19
124,ZEEKR,73.0,195.0,0.0,0.0,195,73
125,ZOTYE,20.0,121.0,20.0,121.0,121,20

In [16]:
df = pd.read_excel("Book 2.xlsx")
df["Lớp (Brand)"] = df["Lớp (Brand)"].replace("MERCEDES", "MERCEDES-BENZ")

In [17]:
df2 = pd.read_excel("accuracy_comparison_horizontal_bar.xlsx")
df2.columns = ["Lớp (Brand)", "Mô hình 15/6/2026 trên tập Train", " Mô hình cũ trên tập cũ", "Mô hình 15/6/2026 trên tập cũ"]
df2

,Lớp (Brand),Mô hình 15/6/2026 trên tập Train,Mô hình cũ trên tập cũ,Mô hình 15/6/2026 trên tập cũ
0,ACURA,1.000000,1.0,1.0
1,AION,0.972727,0.0,0.0
2,ALFA ROMEO,1.000000,1.0,1.0
3,ASIA MOTOR,0.978261,0.0,0.0
4,ASTON MARTIN,0.990196,0.0,0.0
...,...,...,...,...
121,WAW,0.900000,1.0,0.9
122,WEY,0.980769,0.0,0.0
123,WULING,1.000000,1.0,1.0
124,ZEEKR,0.958904,0.0,0.0
125,ZOTYE,1.000000,0.9,1.0

In [18]:
df_merge = pd.merge(df, df2, how='outer')
df_merge.fillna(0, inplace=True)
df_merge.to_excel(
    "Book 3.xlsx", )

In [19]:
df_merge

,Lớp (Brand),Mô hình 1/6/2026 trên tập mới,Mô hình 1/6/2026 trên tập cũ,Mô hình cũ trên tập cũ,Mô hình 15/6/2026 trên tập Train,Mô hình cũ trên tập cũ,Mô hình 15/6/2026 trên tập cũ
0,ACURA,1.0000,1.0,1.0,1.000000,1.0,1.0
1,AION,0.0000,0.0,0.0,0.972727,0.0,0.0
2,ALFA ROMEO,1.0000,1.0,1.0,1.000000,1.0,1.0
3,ASIA MOTOR,0.0000,0.0,0.0,0.978261,0.0,0.0
4,ASTON MARTIN,0.0000,0.0,0.0,0.990196,0.0,0.0
...,...,...,...,...,...,...,...
121,WAW,1.0000,1.0,1.0,0.900000,1.0,0.9
122,WEY,0.0000,0.0,0.0,0.980769,0.0,0.0
123,WULING,1.0000,1.0,1.0,1.000000,1.0,1.0
124,ZEEKR,0.9452,0.0,0.0,0.958904,0.0,0.0
125,ZOTYE,1.0000,1.0,0.9,1.000000,0.9,1.0

In [14]:
df_merge = df_merge.loc[:, ~df_merge.columns.duplicated()]